### ISSUE TITLE
Can't turn off debug mode

### ISSUE THREAD

**Issue by compojoom** [invertase/jet#11]
When tunning packager-jet one isn't able to turn off debug mode off in the emulator. 

The problem seems to come from here:
https://github.com/invertase/jet/blob/master/lib/react-native/index.js#L16

if this is false, then one can turn on the debug mode on, but at some point it also turns off on its own?

**Comment by Salakar** [comment]
Hey

`jetNode` is false when the debugger is not connected to the nodejs instance, it forces itself to debug by calling the native method called debug on android/ios.

Can add in some sort of toggle for this to disable the behavior I guess, though this would mean tests won't run whilst this toggle is on as they can only run during debug.

Thoughts?

**Comment by compojoom** [comment]
The problem is that I don't use this to only write tests.
I'm launching the packager with chrome's debugger as we need to deal with the redux store. And I need to have several emulators open in order to see how the app behaves for different users. 

When debug mode is on on all emulators - I can only use the app with one emulator...

**Comment by pkantsedalov** [comment]
@Salakar Hello. First of all, thank you very much for the tool - it's really nice and helpful.
My question is the next one: how can I run tests _without_ running the debugger at all? I need that for CircleCI.
Previously I ran detox build, then I made a *bundle* and then ran the tests: during the testing detox was able to take the bundle and work with it.
But it seems that jet hangs on test script. After `detox test` it hangs and nothing happens for min 10 minutes (max timeout set by me). I tried both approaches: 

1. run tests without debugger at all fails with an error about the running debugger instance absence; 
2. run tests and debugger in parallel doesn't work - it hangs on CircleCI. No logs, nothing, despite the running detox with *trace* log level.

Please, help.
