### ISSUE TITLE
Difficulty running the referenced project

### ISSUE THREAD

**Issue by gillpeacegood** [invertase/jet#5]
Very excited about this project. Does exactly what I want and long been looking for something that does this.

Unfortunately when trying to run the referenced project I have run into some difficulty. Wasn't sure whether to raise it here or over on react-native-firebase

- I could not get the pod install step to run 

```
CocoaPods could not find compatible versions for pod "RNFirebase":
  In snapshot (Podfile.lock):
    RNFirebase (from `../../ios/RNFirebase.podspec`)
```

- I got an error from packager

Metro Bundler ready.

```
Loading dependency graph, done.
error: bundling failed: ReferenceError: SHA-1 for file .../react-native-firebase/tests/index.android.js is not computed

```

**Comment by Salakar** [comment]
@gillpeacegood welcome! 🎉 The `Podfile.lock` file was out of date on master there. It's updated now though and building fine:

![image](https://user-images.githubusercontent.com/5347038/44798011-60b30300-aba8-11e8-8ec9-3fd9a217a1cd.png)

**Comment by Salakar** [comment]
This is now running on CI with coverage as well :) see the following for more info: https://github.com/invertase/jet/pull/4#issuecomment-419263670
