### ISSUE TITLE
Podspec - incorrect path to source files

### ISSUE THREAD

**Issue by YuliaGrigorieva** [invertase/jet#6]
Hello!

I use cocoa pods in my project and dynamic frameworks for iOS build. 
Unfortunately, Jet is integrated incorrectly to my project via cocoa pods. Jet sources files are not added and compiled in scope of pods project.

The way I add Jet to Podfile:
```
pod 'Jet', :path => '../node_modules/jet/ios/Jet.podspec'
```

Since `s.source_files` should have relative path to the Jet.podspec location, could you please change:
https://github.com/invertase/jet/blob/4177be423bacfea4f8d54862059543f7e325207a/ios/Jet.podspec#L17
to:
```
s.source_files        = '*.{h,m}'
```

Thanks,
Yulia Grigorieva

**Comment by Salakar** [comment]
@YuliaGrigorieva hey thanks, will sort
