### ISSUE TITLE
Test fails to start when using device.launchApp

### ISSUE THREAD

**Issue by compojoom** [invertase/jet#9]
We were launching our tests with the following config:
```
before(async () => {
  // don't launch
  await detox.init(config, {launchApp: false});
  // launch with permissions
  await device.launchApp({permissions: {notifications: 'YES', location: 'always'}});
});

```

unfortunately with jet - this just launches the app, but the tests won't start. If we launch the tests with just:
`await detox.init(config);`

then it works.

**Comment by compojoom** [comment]
Everything works. I didn't like the native libraries...

**Comment by dominicrico** [comment]
@compojoom how did you managed to get this working? Got the same error like you and can't solve it.
